import os, sys
from pathlib import Path
import pandas as pd
import streamlit as st
from dotenv import load_dotenv

ROOT=Path(__file__).resolve().parent
sys.path.insert(0,str(ROOT))
load_dotenv(ROOT/'.env')
try:
    if 'GROQ_API_KEY' in st.secrets: os.environ['GROQ_API_KEY']=st.secrets['GROQ_API_KEY']
    if 'GROQ_MODEL' in st.secrets: os.environ['GROQ_MODEL']=st.secrets['GROQ_MODEL']
except Exception: pass

from src.agent import build_agent
from src import classify_llm, reply as reply_mod, judge as judge_mod

st.set_page_config(page_title='Apple Support Agent',page_icon='🍎',layout='wide')
st.markdown('''<style>.block-container{padding-top:2rem;max-width:1200px}.metric-card{padding:14px;border:1px solid #ddd;border-radius:12px}</style>''',unsafe_allow_html=True)
st.title('🍎 Apple Support AI Agent')
st.caption('Groq-hosted LLM + few-shot classification + TF-IDF retrieval + rule-based escalation + grounded reply generation')

GOLDEN=ROOT/'data/golden/golden_set.csv'
@st.cache_data
def load_golden(): return pd.read_csv(GOLDEN)
@st.cache_resource
def load_agent(): return build_agent(str(ROOT/'data/interim/pairs.parquet'),backend='tfidf')

golden=load_golden()
with st.sidebar:
    st.header('⚙️ Configuration')
    model=os.getenv('GROQ_MODEL','openai/gpt-oss-20b')
    st.code(model)
    key_present=bool(os.getenv('GROQ_API_KEY'))
    st.success('Groq API key detected') if key_present else st.warning('Add GROQ_API_KEY to .env or Streamlit Secrets')
    st.divider()
    st.markdown('**Pipeline**')
    st.markdown('1. Clean input\n2. Groq intent classification\n3. TF-IDF historical retrieval\n4. Escalation policy\n5. Groq grounded reply\n6. Human review only when ESCALATE')
    st.divider()
    st.caption('Golden set is evaluation-only. Threshold tuning is kept separate.')

if 'selected_idx' not in st.session_state: st.session_state.selected_idx=0

mode=st.radio('Input mode',['Test example','Custom query'],horizontal=True)
if mode=='Test example':
    labels=[f"Example #{i+1} — {r.cust_text[:65]}" for i,r in golden.iterrows()]
    idx=st.selectbox('Select test example',range(len(labels)),format_func=lambda i:labels[i],index=st.session_state.selected_idx)
    row=golden.iloc[idx]
    query=st.text_area('Customer Query',row['cust_text'],height=110)
    c1,c2,c3=st.columns(3)
    c1.metric('Expected Intent',row['true_intent'])
    c2.metric('Expected Decision','ESCALATE' if bool(row['should_escalate']) else 'AUTO')
    c3.metric('Dataset','GOLDEN')
else:
    query=st.text_area('Customer Query','Why was I charged more than the estimated fare?',height=110,placeholder='Enter a customer support message...')
    st.caption('Custom queries are not part of the golden evaluation set.')

run=st.button('▶ Run Query',type='primary',use_container_width=True)
if run:
    if not query.strip(): st.error('Enter a customer query.'); st.stop()
    if not key_present: st.error('Groq API key is missing. Add GROQ_API_KEY in .env or Streamlit Secrets.'); st.stop()
    with st.spinner('Running support pipeline...'):
        try: result=load_agent().handle(query.strip())
        except Exception as e: st.error(f'Pipeline error: {e}'); st.stop()
    st.divider(); st.subheader('🤖 Groq Prediction')
    a,b,c,d=st.columns(4)
    a.metric('Intent',result['intent'])
    b.metric('Confidence',f"{result['intent_confidence']*100:.0f}%")
    c.metric('Decision','ESCALATE' if result['escalate'] else 'AUTO')
    d.metric('Retrieval',f"{result['top1_retrieval_score']:.3f}")
    if result['escalate']:
        st.warning(f"Human review required — {result['escalation_reason']}")
    else:
        st.success(f"AUTO — {result['escalation_reason']}")
    left,right=st.columns([1,1])
    with left:
        if result['escalate']:
            st.markdown('### 🤖 AI Suggested Response')
            st.caption('Generated by Groq, but held for human approval because this case was escalated.')
        else:
            st.markdown('### 🤖 AI Auto Response')
            st.caption('Generated by Groq and eligible for automatic sending because the escalation policy passed.')
        if result['draft_reply']:
            st.info(result['draft_reply'])
        else:
            st.error('Groq did not return a response. Check the API key/model and try again.')
    with right:
        st.markdown('### Retrieved Grounding')
        for n,(cust,reply,score) in enumerate(result['grounded_on'],1):
            with st.expander(f'#{n} Similarity {score:.3f}'):
                st.write('**Customer:**',cust); st.write('**Historical reply:**',reply)
    with st.expander('🔍 Full pipeline result'):
        st.json(result)
    if result['escalate']:
        st.divider()
        st.subheader('👤 Human Review')
        st.caption('The AI has prepared a grounded draft, but this case requires a human decision before it can be sent.')

        review_key = f"review_{idx if mode == 'Test example' else 'custom'}_{query}"
        if result['draft_reply']:
            edited = st.text_area('AI draft — edit if needed', result['draft_reply'], height=130, key=review_key)
            r1, r2, r3 = st.columns(3)
            if r1.button('✅ Accept & Approve', key='accept_review', use_container_width=True):
                st.success('Approved. In this demo, the response is marked approved; no real customer messaging system is connected.')
            if r2.button('✏️ Approve Edited', key='edit_review', use_container_width=True):
                if edited.strip():
                    st.success('Edited response approved. In this demo, it is marked approved; no real customer messaging system is connected.')
                else:
                    st.error('The response cannot be empty.')
            if r3.button('❌ Reject / Escalate', key='reject_review', use_container_width=True):
                st.warning('Rejected. Keep this case with human support for a manual response.')
        else:
            manual = st.text_area('Human response', height=130, key=review_key + '_manual')
            if st.button('✅ Approve Human Response', key='approve_manual', use_container_width=True):
                if manual.strip():
                    st.success('Human response approved. No real customer messaging system is connected in this demo.')
                else:
                    st.error('Enter a response before approving.')

    if not result['escalate'] and result['draft_reply']:
        st.divider()
        st.subheader('🚀 Automatic Handling')
        st.success('No human review is required for this case.')
        if st.button('📤 Auto-Send Response (Demo)', key='auto_send', use_container_width=True):
            st.success('Response auto-approved/sent in this demo. No real customer messaging system is connected.')

    if result['draft_reply'] and judge_mod.available():
        if st.button('🧪 Judge generated reply', key='judge_reply'):
            with st.spinner('Scoring with Groq...'):
                score=judge_mod.judge_reply(query,result['draft_reply'],result['grounded_on'])
            st.subheader('LLM Judge')
            cols=st.columns(5)
            for col,axis in zip(cols,['groundedness','correctness','brand_voice','actionability','safety']): col.metric(axis.replace('_',' ').title(),str(score.get(axis,'—'))+'/5')
            st.caption(score.get('rationale',''))

st.divider()
st.caption('For evaluation: do not use the golden set to tune thresholds. Threshold tuning belongs in data/tuning/threshold_tuning.csv; the golden set remains held out.')
